apiVersion: v1
kind: Pod # defines the kind of resources that we will create
metadata: # helps to identify the resource
  labels:
    run: nginx
  name: nginx
spec: # defines the actual specification of the resource
  containers: # defines the containers that we will into the pod
  - image: nginx # image that will be used to create the container
    imagePullPolicy: Always
    name: nginx
    resources:
      limits:
        memory: "200Mi"
        cpu: "200m"
      requests:
        memory: "100Mi"
        cpu: "100m"
    startupProbe:
      exec:
        command:
        - cat
        - /usr/share/nginx/html/index.html
      failureThreshold: 30
      periodSeconds: 10
    readinessProbe:
      httpGet:
        path: /
        port: 80
      initialDelaySeconds: 5
      periodSeconds: 5
    livenessProbe:
      httpGet:
        path: /
        port: 80
      initialDelaySeconds: 5
      periodSeconds: 3
  restartPolicy: Always
