version: "2.4"
services:
  flask:
    build:
      context: .
      dockerfile: Dockerfile
    image: "python-flask-redis"
    ports:
      - "80:5000"
    networks:
      - flask-app-net

  redis:
    image: "redis:alpine"
    networks:
      - flask-app-net
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis-data:/data

networks:
  flask-app-net:
    driver: bridge

volumes:
  redis-data:
